# Generated by Django 5.2.3 on 2025-09-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="course",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
    ]
