# Generated by Django 5.2.3 on 2025-09-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_alter_patient_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="course",
            field=models.CharField(max_length=1000),
        ),
    ]
