# Generated by Django 5.2.3 on 2025-09-20 20:51

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_alter_patient_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="symptomlog",
            name="date_logged",
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
    ]
