# Generated by Django 5.2.3 on 2025-09-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_symptomlog_date_logged"),
    ]

    operations = [
        migrations.AlterField(
            model_name="symptomlog",
            name="date_logged",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
