# Generated by Django 5.2.3 on 2025-10-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_alter_symptomlog_date_logged"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="date_logged",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="symptomlog",
            name="date_logged",
            field=models.DateTimeField(),
        ),
    ]
