version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DATABASE_URL=mysql://root:password@db:3306/medisense_db
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: medisense_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: