services:
  - type: web
    name: medisense
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn medisense.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: medisense-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: medisense-db
    databaseName: medisense
    user: medisense