[theme]
primaryColor = "#3C8640"
backgroundColor = "#1F2A40"
secondaryBackgroundColor = "#141B2D"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
port = 8501
address = "localhost"

[browser]
gatherUsageStats = false