# DigitalOcean App Platform Configuration
name: medisense-app
services:
- name: web
  source_dir: /
  github:
    repo: your-username/your-repo-name
    branch: main
  run_command: gunicorn --bind 0.0.0.0:8080 --workers 3 medisense.wsgi:application
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  dockerfile_path: Dockerfile.production
  http_port: 8080
  envs:
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "False"
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: EMAIL_HOST_PASSWORD
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: ALLOWED_HOSTS
    scope: RUN_AND_BUILD_TIME
    value: "${APP_DOMAIN}"
  - key: CORS_ALLOWED_ORIGINS
    scope: RUN_AND_BUILD_TIME
    value: "https://${APP_DOMAIN}"

databases:
- name: medisense-db
  engine: PG
  version: "14"
  size: basic-xs
  num_nodes: 1

static_sites:
- name: frontend
  source_dir: /frontend/react-admin
  github:
    repo: your-username/your-repo-name
    branch: main
  build_command: npm run build
  output_dir: build
  environment_slug: node-js
  envs:
  - key: REACT_APP_API_URL
    scope: BUILD_TIME
    value: "https://${web.DEPLOYED_URL}/api"
