# Generated by Django 5.2.3 on 2025-09-21 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Painkiller", "Painkiller"),
                            ("Antibiotic", "Antibiotic"),
                            ("Antiseptic", "Antiseptic"),
                            ("Supplement", "Supplement"),
                            ("Cough Relief", "Cough Relief"),
                            ("Equipment", "Equipment"),
                            ("First Aid", "First Aid"),
                        ],
                        default="Painkiller",
                        max_length=50,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("pcs", "Pieces"),
                            ("bottles", "Bottles"),
                            ("tabs", "Tablets"),
                            ("ml", "Milliliters"),
                            ("g", "Grams"),
                        ],
                        default="pcs",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("In Stock", "In Stock"),
                            ("Low Stock", "Low Stock"),
                            ("Out of Stock", "Out of Stock"),
                        ],
                        default="In Stock",
                        max_length=20,
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
