# Generated by Django 5.2.3 on 2025-07-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="budget",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="stock",
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("Painkiller", "Painkiller"),
                    ("Antibiotic", "Antibiotic"),
                    ("Antiseptic", "Antiseptic"),
                    ("Supplement", "Supplement"),
                    ("Cough Relief", "Cough Relief"),
                    ("Equipment", "Equipment"),
                    ("First Aid", "First Aid"),
                ],
                default="Painkiller",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="date_added",
            field=models.DateField(default="2024-01-01"),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("In Stock", "In Stock"),
                    ("Low Stock", "Low Stock"),
                    ("Out of Stock", "Out of Stock"),
                ],
                default="In Stock",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="unit",
            field=models.CharField(
                choices=[
                    ("pcs", "Pieces"),
                    ("bottles", "Bottles"),
                    ("tabs", "Tablets"),
                    ("ml", "Milliliters"),
                    ("g", "Grams"),
                ],
                default="pcs",
                max_length=20,
            ),
        ),
    ]
